baseURL = "https://2cloudlab.com/"
languageCode = "en-us"
title = "2cloudlab | 企业数字化转型的催化剂"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "关于"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "服务"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "价格"
        url     = "price"
        weight  = 4
    [[menu.nav]]
        name    = "博客"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "NoSQL"
        url     = "nosql"
        weight  = 6
    [[menu.nav]]
        name    = "联系我们"
        url     = "contact"
        weight  = 7

# Site Params
[params]
    home = "首页"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "2cloudlab是云计算解决方案提供商，致力于云计算和DEVOPS。我们渴望通过云计算技术来帮助企业进行数字化转型。提高企业的研发效率、降低企业的研发成本以及加快企业的创新速度是我们成立的初衷！"
    author = "2cloudlab"
    # Google Analitycs
    googleAnalitycsID = "UA-171018621-1"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "2cloudlab是云计算解决方案提供商，致力于"
        description = "2cloudlab为企业准备产品的运行环境，只需要1天！我们渴望通过云计算技术来帮助企业进行数字化转型。提高企业的研发效率、降低企业的研发成本以及加快企业的创新速度是我们成立的初衷！"
        btn     = true
        btnText = "如何使用2cloudlab的服务"
        btnURL  = "/blog/how-to-use-2cloudlab-services/"
        [[params.banner.flipText]]
            title   = "云计算"
        [[params.banner.flipText]]
            title   = "DevOps"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "关于我们"
        content = "这里是<strong>2cloudlab</strong>，由一群活跃于长三角地区（上海）的IT精英组成。这里的人曾埋伏于各个传统行业，深谙传统行业在数字化转型过程中所遇到的阻碍。好在这帮人精通云计算技术，编写了大量简洁、可信度高和易于复用的代码，知道采用哪些技术手段来帮助企业快速转型。<br> <br> <b>2cloudlab</b>成立的初衷是通过云计算技术帮助企业数字化转型、降低企业研发成本和提高企业生产效率。这里的人以经验和技术为优势，致力于向企业提供开箱即用的云端解决方案或最佳实践。"
        image   = "images/about/about.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "听起来还不错 ？"
        content = "如果你所在的企业遇到了以下问题：<br> 研发流程混乱不堪或者效率低下、经历了持续上升的运维成本、无法及时向用户发布新的服务或产品以及想使用云计算技术但缺乏经验！<br>那么，请毫不犹疑地"
        btnText = "联系我们"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "开箱即用的解决方案"
        subtitle= "企业的数字化转型是分阶段进行的。一般需要解决网络互联、数据存储、邮箱系统、源码托管、建设研发流水线以及研发产品等等。以下列举了每个企业都会面临的常见问题所对应的解决方案。"

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "https://github.com/2cloudlab"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "https://www.linkedin.com/company/2cloudlab-com"

[markup]
    [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = false
      style = "friendly"
      tabWidth = 4